name: Build and Deploy Backend

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name:
        run: |
          echo "Let's start building the backend container image and deploying it to Rahti!" 

      - name: Build container image
        run: docker build -t ville/backend:test .

      - name: Log in to registry
        run: echo "${{ secrets.REGISTRY_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push image
        run: docker push ghcr.io/${{ github.repository }}/backend:${{ github.sha }}

      - name: Deploy to Rahti
        run: |
          oc login --token=${{ secrets.RAHTI_TOKEN }} --server=${{ secrets.RAHTI_SERVER }}
          oc set image deployment/backend backend=ghcr.io/${{ github.repository }}/backend:${{ github.sha }}